### ISSUE TITLE
install problem due to pbr weirdness + possible solution

### ISSUE THREAD

**Issue by lebedov** [seninp/saxpy#2]
When I tried to install saxpy by cloning the repo and running `python setup.py install` with Python 3.6.3 and all of the requirements already installed, I observed the following exception:

```                                                                                                   
ERROR:root:Error parsing                                                                                                                                                                           
Traceback (most recent call last):                                                                                                                                                                 
  File "/home/lebedov/saxpy/.eggs/pbr-3.1.1-py3.6.egg/pbr/core.py", line 111, in pbr                                                                                                     
    attrs = util.cfg_to_args(path, dist.script_args)                                                                                                                                               
  File "/home/lebedov/saxpy/.eggs/pbr-3.1.1-py3.6.egg/pbr/util.py", line 267, in cfg_to_args                                                                                             
    wrap_commands(kwargs)                                                                                                                                                                          
  File "/home/lebedov/saxpy/.eggs/pbr-3.1.1-py3.6.egg/pbr/util.py", line 569, in wrap_commands                                                                                           
    cmdclass = ep.resolve()                                                                                                                                                                        
  File "/home/lebedov/miniconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2437, in resolve                                                                                    
    module = __import__(self.module_name, fromlist=['__name__'], level=0)                                                                                                                          
ModuleNotFoundError: No module named 'tasks'                                                                                                                                                       
error in setup command: Error parsing /home/lev/Work/projects/saxpy/setup.cfg: ModuleNotFoundError: No module named 'tasks'  
```

This seems to be due to some weirdness in [pbr](https://docs.openstack.org/pbr/latest/) that appears to have affected other Python packages. Installing the [cli_helpers](https://github.com/dbcli/cli_helpers) package resolved the problem; perhaps it should be added to `setup_requires` in `setup.py`?

**Comment by seninp** [comment]
Sorry for the delay, I'll try to reproduce over the weekend and will fix then. Thank you for the feedback!
